name: ci

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: |
          npm ci
          npm run build
          mv build/ docs/
          git add -f docs
        env:
          CI: false
      - name: Push
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "$MESSAGE"
          git push origin main:ci -f